### ISSUE TITLE
Ruby syntax error with Ruby 2.1.3p242

### ISSUE THREAD

**Issue by jhammerman79** [nvwls/zap#26]
When I run berks upload I get:

E, [2015-08-11T12:03:20.227174 #9278] ERROR -- : Cookbook file attributes/PaxHeader/groups.rb has a ruby syntax error:
E, [2015-08-11T12:03:20.227627 #9278] ERROR -- : /home/jhammerman/.berkshelf/cookbooks/zap-0.8.6/attributes/PaxHeader/groups.rb:1: syntax error, unexpected tIDENTIFIER, expecting end-of-input
E, [2015-08-11T12:03:20.227790 #9278] ERROR -- : 18 gid=1933861586
E, [2015-08-11T12:03:20.227929 #9278] ERROR -- :       ^
E, [2015-08-11T12:03:20.276937 #9278] ERROR -- : Ridley::Errors::CookbookSyntaxError: Invalid ruby files in cookbook: zap (0.8.6).

I know that Zap worked fine with this Ruby version in Zap version 0.8.4, so this issue must have been introduced in the current version or the previous one.

I'm happy to install RVM, but it would be great to know what version of Ruby the cookbook will work with  to reduce my trial and error time.

Thanks,
Joseph Hammerman

**Comment by sbotman** [comment]
Hi Joseph,

I have seen this error before and resolved this by updating to at least version 3.2.0 of berkshelf.
You will also need to delete the cookbook from your ~/.berkshelf cache because the PaxHeader directories are removed on download and not on upload, see:
https://github.com/berkshelf/berkshelf/blob/master/lib/berkshelf/community_rest.rb#L22

HTH,
Sander

**Comment by nvwls** [comment]
The zap cookbook does not contain PaxHeader directories. As Sander says, this is an environment issue.
