### ISSUE TITLE
Zap Cookbook from Supermarket Doesn't Work with Test Kitchen

### ISSUE THREAD

**Issue by specialkevin** [nvwls/zap#32]
When I try and use the zap cookbook from the supermarket it breaks test-kitchen. This is due to PaxHeader directories being included from the upload. More info on the wide scope of this problem can be found here, https://github.com/chef/chef/issues/1660. A quick fix for this would be to re-upload the zap cookbook to the supermarket and ensure that those PaxHeader directories aren't present.

**Comment by sbotman** [comment]
Are you using berkshelf? Looking at the ticket berkshelf 3.1.4 was used. `Resolving cookbook dependencies with Berkshelf 3.1.4...`  It should be solved here: https://github.com/berkshelf/berkshelf/pull/1313. And I believe this was fixed with version 3.2.0 and up. But I agree, we should remove the annoying headers from the file, so hopefully @nvwls can help you out with this.

**Comment by specialkevin** [comment]
I am using Berkshelf and the version I have is later than 3.2.0. 

berks --version
4.0.1

**Comment by nvwls** [comment]
I uploaded `v0.11.4` using stove. This should resolve the issue.
